on:
  repository_dispatch:
    types: [repo_updated]
concurrency: 
  group: singleton
  cancel-in-progress: false

jobs:
  update-issue-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout the plugin repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          fetch-depth: 0
          path: current-plugin
      - name: Process plugin
        run: ./update-cloned-plugin.py "${{ github.event.client_payload.repo }}"
      - run: ./generate.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Auto-updating ${{ github.event.client_payload.repo }}"
          add: "plugins docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
