on:
  repository_dispatch:
    types: [update]
  push:
    paths:
      - 'plugins/**'

concurrency: 
  group: singleton
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./generate.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Changes from ${{ github.sha }}"
          add: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
