on:
  repository_dispatch:
    types: [update]
  push:
    paths:
      - 'plugins/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent wait for concurrent jobs
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 20 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./generate.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Changes from ${{ github.sha }}"
          add: "docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
